version: "3.8"

services:
  frontend:
    image: ashankguptaa/courier-frontend:latest
    container_name: courier-frontend
    ports:
      - "5173:5173"
    restart: always
    environment:
      - VITE_API_BASE_URL=http://localhost:4300
    networks:
      - courrier-tracking

  backend:
    image: ashankguptaa/courier-backend:latest
    container_name: courier-backend
    ports:
      - "4300:4300"
    restart: always
    environment:
      - PORT=4300
      - JWT_SECRET=aloopuri
    networks:
      - courrier-tracking

networks:
  courrier-tracking:
